version: 2
enable-beta-ecosystems: true

multi-ecosystem-groups:
  ruff:
    schedule:
      interval: "weekly"

  ty:
    schedule:
      interval: "weekly"


updates:
  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: "ruff"
    patterns: ["ruff"]

  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: "ty"
    patterns: ["ty"]

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
          - "prek"
      test:
        patterns:
          - "aioresponses"
          - "freezegun"
          - "pytest"
          - "pytest-*"
          - "syrupy"
    ignore:
      - dependency-name: "aiohttp"
      - dependency-name: "tenacity"
      - dependency-name: "dacite"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ci:
        patterns: ["*"]

  - package-ecosystem: "pre-commit"
    directory: "/"
    multi-ecosystem-group: "ruff"
    patterns: ["*ruff-pre-commit"]

  - package-ecosystem: "pre-commit"
    directory: "/"
    multi-ecosystem-group: "ty"
    patterns: ["*ty-pre-commit"]

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pre-commit:
        patterns: ["*"]
